# Generated by Django 4.2.10 on 2024-08-26 07:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_At', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_At', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('food_type', models.PositiveSmallIntegerField(choices=[(1, 'Carbohydrate'), (2, 'Protein'), (3, 'Fat')])),
                ('amount', models.PositiveSmallIntegerField(default=0)),
                ('amout_type', models.PositiveSmallIntegerField(choices=[(1, 'Cup'), (2, 'Gram'), (3, 'Piece')], default=2)),
                ('calories', models.FloatField(max_length=30)),
                ('protein', models.FloatField(max_length=30)),
                ('fat', models.FloatField(max_length=30)),
                ('carbohydrate', models.FloatField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
