# Generated by Django 4.2.10 on 2024-08-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Carbohydrate'), (2, 'Protein'), (3, 'Fat'), (4, 'Fruits'), (5, 'Milk'), (6, 'Vegetables')]),
        ),
    ]
