# Generated by Django 4.2.10 on 2024-08-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_food_food_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='calcium',
            field=models.FloatField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='food',
            name='cholesterol',
            field=models.FloatField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='food',
            name='iron',
            field=models.FloatField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='food',
            name='sodium',
            field=models.FloatField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='food',
            name='vitamin_A',
            field=models.FloatField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='food',
            name='vitamin_C',
            field=models.FloatField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.FloatField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbohydrate',
            field=models.FloatField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.FloatField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.FloatField(default=0, max_length=30),
        ),
    ]
